version: 2

registries:
  github-private:
    type: git
    url: https://github.com
    username: x-access-token
    password: ${{secrets.DEPENDABOT_GITHUB_TOKEN}}

updates:
  - package-ecosystem: gomod
    directory: /

    schedule:
      interval: daily

    registries:
      - github-private

    commit-message:
      prefix: "build(deps) [PE-/]"

    allow:
      - dependency-name: "github.com/shopuptech/*"
      - dependency-name: "github.com/voonik/*"

    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
      - dependency-name: "github.com/shopuptech/event-bus-logs-go"
      - dependency-name: "github.com/voonik/goConnect"
      - dependency-name: "github.com/voonik/goFramework"
      - dependency-name: "github.com/shopuptech/event-bus-consumer-go"

    groups:
      private:
        patterns:
          - "github.com/shopuptech/*"
          - "github.com/voonik/*"
        update-types:
          - "minor"
          - "patch"
