// Code generated by "stringer -type=AccountSubType"; DO NOT EDIT.

package utils

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Current-1]
	_ = x[Savings-2]
	_ = x[Bkash-3]
	_ = x[Nagada-4]
	_ = x[EBL-5]
	_ = x[UCBL-6]
}

const _AccountSubType_name = "CurrentSavingsBkashNagadaEBLUCBL"

var _AccountSubType_index = [...]uint8{0, 7, 14, 19, 25, 28, 32}

func (i AccountSubType) String() string {
	i -= 1
	if i >= AccountSubType(len(_AccountSubType_index)-1) {
		return "AccountSubType(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _AccountSubType_name[_AccountSubType_index[i]:_AccountSubType_index[i+1]]
}
