// Code generated by "stringer -type=AccountType"; DO NOT EDIT.

package utils

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Bank-1]
	_ = x[Mfs-2]
	_ = x[PrepaidCard-3]
}

const _AccountType_name = "BankMfsPrepaidCard"

var _AccountType_index = [...]uint8{0, 4, 7, 18}

func (i AccountType) String() string {
	i -= 1
	if i >= AccountType(len(_AccountType_index)-1) {
		return "AccountType(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _AccountType_name[_AccountType_index[i]:_AccountType_index[i+1]]
}
