// Code generated by "stringer --type=ActivationState"; DO NOT EDIT.

package utils

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[NOT_ACTIVATED-1]
	_ = x[DOWNLOADED_EXCEL-1]
	_ = x[ACTIVATED-1]
	_ = x[VERIFICATION_PENDING-1]
	_ = x[HOLD_OFF-1]
	_ = x[PRE_ACTIVATED-1]
	_ = x[PENDING_QUALITY-1]
	_ = x[POLICY_VIOLATED-1]
	_ = x[FULFILMENT_VIOLATED-1]
	_ = x[VACATION_PENDING-1]
	_ = x[SUSPENDED-1]
	_ = x[BLOCKED-1]
	_ = x[FRAUD-1]
	_ = x[ON_HOLD-1]
	_ = x[GST_PENDING-1]
	_ = x[UNDER_REVIEW-1]
}

const _ActivationState_name = "NOT_ACTIVATED"

var _ActivationState_index = [...]uint8{0, 13}

func (i ActivationState) String() string {
	i -= 1
	if i >= ActivationState(len(_ActivationState_index)-1) {
		return "ActivationState(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _ActivationState_name[_ActivationState_index[i]:_ActivationState_index[i+1]]
}
