// Code generated by "stringer -type=BusinessUnit"; DO NOT EDIT.

package utils

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[UNICORN-1]
	_ = x[UNBRANDED-2]
	_ = x[BRANDED-3]
	_ = x[LIFESTYLE-4]
	_ = x[BLITZ-5]
	_ = x[AGRO-6]
	_ = x[WHOLESALE-7]
	_ = x[MWS-8]
	_ = x[FRESH-9]
	_ = x[POULTRY-10]
	_ = x[APPAREL-11]
	_ = x[INFRA-12]
	_ = x[ENERGY-13]
	_ = x[ELECTRONICS-14]
	_ = x[MOKAM_X-15]
	_ = x[AGRO_FISH_PROJECT-16]
	_ = x[POP_BOISHAKHI-17]
	_ = x[REDX_FULFILLMENT_SERVICE-18]
	_ = x[REDX_FULFILLMENT_SERVICE2-19]
}

const _BusinessUnit_name = "UNICORNUNBRANDEDBRANDEDLIFESTYLEBLITZAGROWHOLESALEMWSFRESHPOULTRYAPPARELINFRAENERGYELECTRONICSMOKAM_XAGRO_FISH_PROJECTPOP_BOISHAKHIREDX_FULFILLMENT_SERVICEREDX_FULFILLMENT_SERVICE2"

var _BusinessUnit_index = [...]uint8{0, 7, 16, 23, 32, 37, 41, 50, 53, 58, 65, 72, 77, 83, 94, 101, 118, 131, 155, 180}

func (i BusinessUnit) String() string {
	i -= 1
	if i >= BusinessUnit(len(_BusinessUnit_index)-1) {
		return "BusinessUnit(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _BusinessUnit_name[_BusinessUnit_index[i]:_BusinessUnit_index[i+1]]
}
