// Code generated by "stringer --type=FileType"; DO NOT EDIT.

package utils

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[SecurityCheque-1]
	_ = x[GuarantorNID-2]
	_ = x[TIN-3]
	_ = x[BIN-4]
}

const _FileType_name = "SecurityChequeGuarantorNIDTINBIN"

var _FileType_index = [...]uint8{0, 14, 26, 29, 32}

func (i FileType) String() string {
	i -= 1
	if i >= FileType(len(_FileType_index)-1) {
		return "FileType(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _FileType_name[_FileType_index[i]:_FileType_index[i+1]]
}
