// Code generated by "stringer -type=ServiceType"; DO NOT EDIT.

package utils

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Supplier-1]
	_ = x[Transporter-2]
	_ = x[RentVendor-3]
	_ = x[MwsOwner-4]
	_ = x[DoBuyer-5]
	_ = x[ProcurementVendor-6]
	_ = x[Employee-7]
	_ = x[Vendor-8]
	_ = x[OfficeSuppliesAndConsumables-9]
	_ = x[LogisticsAndTransportation-10]
	_ = x[CleaningAndMaintenance-11]
	_ = x[ProfessionalServices-12]
	_ = x[UtilitiesAndCommunication-13]
	_ = x[EmployeeAndClientRelations-14]
	_ = x[Insurance-15]
}

const _ServiceType_name = "SupplierTransporterRentVendorMwsOwnerDoBuyerProcurementVendorEmployeeVendorOfficeSuppliesAndConsumablesLogisticsAndTransportationCleaningAndMaintenanceProfessionalServicesUtilitiesAndCommunicationEmployeeAndClientRelationsInsurance"

var _ServiceType_index = [...]uint8{0, 8, 19, 29, 37, 44, 61, 69, 75, 103, 129, 151, 171, 196, 222, 231}

func (i ServiceType) String() string {
	i -= 1
	if i >= ServiceType(len(_ServiceType_index)-1) {
		return "ServiceType(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _ServiceType_name[_ServiceType_index[i]:_ServiceType_index[i+1]]
}
