// Code generated by "stringer -type=ServiceType"; DO NOT EDIT.

package utils

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Supplier-1]
	_ = x[Transporter-2]
}

const _ServiceType_name = "SupplierTransporter"

var _ServiceType_index = [...]uint8{0, 8, 19}

func (i ServiceType) String() string {
	i -= 1
	if i >= ServiceType(len(_ServiceType_index)-1) {
		return "ServiceType(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _ServiceType_name[_ServiceType_index[i]:_ServiceType_index[i+1]]
}
