// Code generated by "stringer -type=StateReason"; DO NOT EDIT.

package utils

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[POLICY_VIOLATION-1]
	_ = x[FULFILMENT_VIOLATION-2]
	_ = x[PERFORMANCE-3]
	_ = x[PRODUCT_QUALITY-4]
	_ = x[PENDING_RISK_REVIEW-5]
	_ = x[PENDING_CONTACT_WITH_SS-6]
	_ = x[VACATION_MODE-7]
}

const _StateReason_name = "POLICY_VIOLATIONFULFILMENT_VIOLATIONPERFORMANCEPRODUCT_QUALITYPENDING_RISK_REVIEWPENDING_CONTACT_WITH_SSVACATION_MODE"

var _StateReason_index = [...]uint8{0, 16, 36, 47, 62, 81, 104, 117}

func (i StateReason) String() string {
	i -= 1
	if i < 0 || i >= StateReason(len(_StateReason_index)-1) {
		return "StateReason(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _StateReason_name[_StateReason_index[i]:_StateReason_index[i+1]]
}
