// Code generated by "stringer --type=SupplierType"; DO NOT EDIT.

package utils

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[L0-1]
	_ = x[L1-2]
	_ = x[L2-3]
	_ = x[L3-4]
	_ = x[Hlc-5]
	_ = x[Captive-6]
	_ = x[Driver-7]
	_ = x[CashVendor-8]
	_ = x[RedxHubVendor-9]
}

const _SupplierType_name = "L0L1L2L3HlcCaptiveDriverCashVendorRedxHubVendor"

var _SupplierType_index = [...]uint8{0, 2, 4, 6, 8, 11, 18, 24, 34, 47}

func (i SupplierType) String() string {
	i -= 1
	if i >= SupplierType(len(_SupplierType_index)-1) {
		return "SupplierType(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _SupplierType_name[_SupplierType_index[i]:_SupplierType_index[i+1]]
}
