secret = ["12","34", "34", "56","56","56","45"]

[logconfig]
logger = "logrus"
level = "info"

[traceconfig]
host = "localhost"
port = "6832"
servicename = "ss2"
type = "const"
param = 1


[grpcserverconfig]
port = "5006"
reflection=true

[serviceconfig]
name = "ss2"
originalName = "ss2"