secret = ["12", "34", "34", "56", "56", "56", "45"]

[logconfig]
logger = "logrus"
level = "info"

[traceconfig]
host = "localhost"
port = "6832"
servicename = "ss2"
type = "const"
param = 1

[grpcserverconfig]
port = "5006"
reflection = true

[gRPCAddOnAPIServices]
AppPreferenceAPI = true

[serviceconfig]
name = "ss2"
originalName = "ss2"

[cloudStorageConfig]
serviceAccount = "config/service-account.json"

[asynqConfig]
teamName = "mokam"
serviceName = "sc2_admin"
poolSize = 10
rabbitMQURL = "amqp://admin:admin@localhost"
enabled = false

[statsdconfig]
host = "localhost"
port = "8125"
enabled = false
