// Code generated by mockery v2.39.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	user_mapping "github.com/voonik/goConnect/api/go/oms/user_mapping"
)

// OmsApiHelperInterface is an autogenerated mock type for the OmsApiHelperInterface type
type OmsApiHelperInterface struct {
	mock.Mock
}

// FetchUserMappingData provides a mock function with given fields: ctx, userIDs
func (_m *OmsApiHelperInterface) FetchUserMappingData(ctx context.Context, userIDs []uint64) (*user_mapping.UserMappingResponse, error) {
	ret := _m.Called(ctx, userIDs)

	if len(ret) == 0 {
		panic("no return value specified for FetchUserMappingData")
	}

	var r0 *user_mapping.UserMappingResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []uint64) (*user_mapping.UserMappingResponse, error)); ok {
		return rf(ctx, userIDs)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []uint64) *user_mapping.UserMappingResponse); ok {
		r0 = rf(ctx, userIDs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*user_mapping.UserMappingResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []uint64) error); ok {
		r1 = rf(ctx, userIDs)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewOmsApiHelperInterface creates a new instance of OmsApiHelperInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOmsApiHelperInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *OmsApiHelperInterface {
	mock := &OmsApiHelperInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
