name: Cypress Trigger Execution

on:
  issue_comment:
    types: [created, edited]

jobs:
  cypress-tests:
    uses: shopuptech/cypressautomation/.github/workflows/prTrigger.yml@master
    secrets: inherit