name: Deploy2Prod
on:
  release:
    types: [published]

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GKE_PRODUCTION_CLUSTER: ${{ secrets.GKE_PRODUCTION_CLUSTER }}    # TODO: update to cluster name
  GKE_ZONE: ${{ secrets.GKE_ZONE }}   # TODO: update to cluster zone
  GITHUB_TOKEN: ${{ secrets.PAT_GITHUB }}

jobs:
  docker-build:
    name: Setup, Build, Publish, and Deploy to staging
    uses: shopuptech/shopup-cicd-git-actions/.github/workflows/build-docker.yml@master
    with:
      BUILD_NAME: "ss2"
      DOCKER_FILE_PATH: "docker/Dockerfile"
      IMAGE_TAG: ${{ github.ref_name }}
      IMAGE_PATH: "gcr.io/voonik-tech/vnkshopup/ss2"
      WORKLOAD_PROVIDER: "projects/144345706419/locations/global/workloadIdentityPools/github-actions/providers/github"
      SERVICE_ACCOUNT: "circleci@voonik-tech.iam.gserviceaccount.com"
    secrets:
      BUILD_ARG: --build-arg GITHUB_TOKEN="${{secrets.GIHUB_PAT}}"

  update-proto-config:
    needs: docker-build
    uses: shopuptech/shopup-cicd-git-actions/.github/workflows/update-proto-config.yml@master
    with:
      GOCONNECT_DIRECTORIES: 'ss2,health,app_preference_service'
      NAMESPACE: "mokam"
      PB_FILE_NAME: "supplier.pb"
      PROTO_BIN_NAME: "ss2-proto-bin"
      LOCATION: "asia-southeast1"
      CLUSTER_NAME: "mokam-production-autopilot"
      WORKLOAD_PROVIDER: "projects/144345706419/locations/global/workloadIdentityPools/github-actions/providers/github"
      SERVICE_ACCOUNT: "circleci@voonik-tech.iam.gserviceaccount.com"
    secrets:
      ACCESS_TOKEN: ${{ secrets.GIHUB_PAT}}

  deploy-prod:
    needs: update-proto-config
    uses: shopuptech/shopup-cicd-git-actions/.github/workflows/go-deployment.yml@go-deploy
    with:
      APP_NAME: "ss2"
      IMAGE_TAG: ${{ github.ref_name }}
      valueFile: "charts/shopup/ss2/values-production-autopilot.yaml"
      customValues: ${{ needs.update-proto-config.outputs.GOCONNECT_SERVICE_NAMES }}
    secrets:
      GIHUB_PAT: ${{ secrets.GIHUB_PAT }}