name: Golang Unit Testing

on: ["push"]

env:
  SOURCE_BRANCH_NAME: ${{ github.event.pull_request.head.ref }}
  GOPRIVATE: github.com/voonik

jobs:
  tests:
    name: Unit Testing
    runs-on: ubuntu-latest
    services:
      # How to use Mysql
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: password
        ports:
        - 33306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

      # How to use Redis
      redis:
        image: redis
        ports:
        - 6379/tcp

    steps:  
      - name: Setup Env Vars and work dir
        run: |
          test -d "GoLang/src/github.com/voonik/sr_service" || mkdir -p "GoLang/src/github.com/voonik/sr_service"

      - name: Checkout code
        uses: actions/checkout@v2
        with:
          path: GoLang/src/github.com/voonik/ss2

      - name: Install SSH keys
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: "Add known public keys of github here"

      - name: Verify MySQL
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential python-dev nginx-extras pkg-config cmake libxrender1 libmysqlclient-dev ncurses-dev gettext flex bison autoconf binutils-doc redis-tools vim nfs-common jq bc
          mysql --host 127.0.0.1 --port 33306 -uroot -ppassword -e "SHOW GRANTS FOR 'root'@'localhost'"
          mysql_tzinfo_to_sql /usr/share/zoneinfo | mysql --host 127.0.0.1 --port 33306 -uroot -ppassword mysql

      - name: Setup GO
        uses: actions/setup-go@v2
        with:
          go-version: '1.16.3'

      - name: Create DB
        env:
          ENV: test
        run: |
          touch create_db.sql
          echo "create database ss2_test;" >> create_db.sql
          mysql --host 127.0.0.1 --port 33306 -uroot -ppassword  < create_db.sql

      - name: Run tests
        env:
          ENV: test
        run: |
          git config --global --add url."git@github.com:".insteadOf "https://github.com/"
          export PATH=$PATH:GoLang/bin
          cd GoLang/src/github.com/voonik/ss2
          go mod download
          go get -u github.com/jstemmer/go-junit-report
          go get github.com/mikefarah/yq/v4
          go mod vendor
          bash run_tests.sh

      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        with:
          projectBaseDir: GoLang/src/github.com/voonik/ss2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v2
        with:
          report_paths: '**/GoLang/src/github.com/voonik/ss2/*.xml'
        


